name: ireceipt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.3
  auto_route_generator: ^5.0.3
  camera: ^0.9.3+1
  cloud_firestore: ^4.4.4
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  ensure_initialized: ^0.1.0
  equatable: ^2.0.5
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^3.0.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.0
  google_ml_kit: ^0.13.0
  image_picker: ^0.7.2+1
  json_annotation: ^4.8.0
  lottie: ^2.2.0
  path_provider: ^2.0.12
  string_similarity: ^2.0.0
  super_string: ^1.0.3
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/animations/

